version: '3'
services:
  websockets-chat-serverside:
    build:
      context: ./websockets-chat-serverside
      dockerfile: Dockerfile
    container_name: websockets-chat-serverside
    ports:
      - 3036:3000
    volumes:
      - ./websockets-chat-serverside:/app
      - ./websockets-chat-serverside/node_modules:/app/node_modules

  websockets-chat-clientside:
    build:
      context: ./websockets-chat-clientside
      dockerfile: Dockerfile
    container_name: websockets-chat-clientside
    ports:
      - "80:80"
    volumes:
      - ./websockets-chat-clientside:/app
      - ./websockets-chat-clientside/node_modules:/app/node_modules