version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 3036:3000
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules